apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: oficina-app
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-app
    app.kubernetes.io/part-of: oficina-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oficina-app
