apiVersion: v1
kind: Service
metadata:
  name: oficina-db
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-db
    app.kubernetes.io/part-of: oficina-backend
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oficina-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
