apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oficina-db-pvc
  namespace: oficina
  labels:
    app.kubernetes.io/part-of: oficina-backend
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
